development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root
  host: localhost
  database: 1501_252_condominium

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: 
  host: localhost
  database: 1501_252_condominium
